name: Mind Matters
favicon: null
layout_spectrum: 0.74969
typography_spectrum: 0.46501
title: Mind Matters
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a1b963'
    - '#7b8f50'
    - '#442d68'
    - '#685886'
  brandStrength: 1
  lightness: 0.375
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
