name: Mind Matters 365
favicon: null
layout_spectrum: 0.74969
typography_spectrum: 0.46501
title: Mind Matters 365
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-39145417-4
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#9383ca'
    - '#acc90c'
    - '#cacaca'
    - '#d8908d'
  brandStrength: 0.625
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
