name: Mind Matters
favicon: null
layout_spectrum: 0.629305869108066
typography_spectrum: 0.467386644333601
title: Mind Matters
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9751964535098523
  lightness: 0.7900147461332381
  saturation: 0.12235359335318208
  rhythmicContrast: 0.09717085445299745
purpose: []
